# .github/workflows/deploy-docker.yml
name: Deploy Docker

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/coqui-ai/tts-cpu:latest

      - name: Run Docker container
        run: |
          docker run --rm -d -p 5002:5002 ghcr.io/coqui-ai/tts-cpu
          sleep 10  # Đợi một chút để server khởi động
          curl http://localhost:5002  # Kiểm tra xem server có hoạt động không
